# Generated by Django 6.0.2 on 2026-03-26 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('anime', 'Anime'), ('tv', 'TV Show'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book')], max_length=10)),
                ('wiki_slug', models.CharField(blank=True, max_length=255)),
                ('wiki_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('pr', 'Processing'), ('c', 'Completed'), ('f', 'Failed')], default='p', max_length=2)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('wiki_page', models.URLField(blank=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='book_trees.mediarequest')),
            ],
            options={
                'ordering': ['-mention_count'],
                'unique_together': {('media', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('relationship_subtype', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('character_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_character_1', to='book_trees.character')),
                ('character_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_character_2', to='book_trees.character')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='book_trees.mediarequest')),
            ],
            options={
                'unique_together': {('media', 'character_1', 'character_2', 'relationship_type')},
            },
        ),
    ]
