# Generated by Django 6.0.2 on 2026-03-31 01:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('anime', 'Anime'), ('tv', 'TV Show'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book')], max_length=10)),
                ('wiki_slug', models.CharField(blank=True, max_length=255)),
                ('wiki_url', models.URLField(blank=True)),
                ('resolution_strategy', models.CharField(blank=True, choices=[('dedicated_scoped', 'Dedicated wiki, scoped category'), ('umbrella_scoped', 'Umbrella wiki, scoped category'), ('dedicated_unscoped', 'Dedicated wiki, unscoped category'), ('no_category', 'No useful character category')], default='', max_length=20)),
                ('chosen_category', models.CharField(blank=True, default='', max_length=500)),
                ('metadata_categories', models.JSONField(blank=True, default=list)),
                ('strategy_reasoning', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('pr', 'Processing'), ('c', 'Completed'), ('f', 'Failed'), ('ns', 'Needs Scope'), ('nc', 'No Category')], default='p', max_length=2)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('wiki_page', models.URLField(blank=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='book_trees.mediarequest')),
            ],
            options={
                'ordering': ['-mention_count'],
                'unique_together': {('media', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='book_trees.mediarequest')),
                ('source', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rels', to='book_trees.character')),
                ('target', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rels', to='book_trees.character')),
            ],
            options={
                'unique_together': {('media', 'source', 'target')},
            },
        ),
    ]
