# Generated by Django 6.0.2 on 2026-04-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarequest',
            name='creators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediarequest',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediarequest',
            name='release_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='mediarequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('pr', 'Processing'), ('c', 'Completed'), ('f', 'Failed'), ('ns', 'Needs Scope'), ('nc', 'No Category'), ('dup', 'Duplicate')], default='p', max_length=3),
        ),
    ]
