# Generated by Django 6.0.2 on 2026-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarequest',
            name='metadata_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
