# Generated by Django 4.2.27 on 2025-12-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0002_alter_epubfile_status_character_relationship_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='annotated_sentences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
