# Generated by Django 6.0.2 on 2026-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0002_mediarequest_metadata_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarequest',
            name='resolution_strategy',
            field=models.CharField(blank=True, choices=[('dedicated_scoped', 'Dedicated wiki, scoped category'), ('umbrella_scoped', 'Umbrella wiki, scoped category'), ('dedicated_unscoped', 'Dedicated wiki, unscoped category'), ('no_category', 'No useful character category')], default='', max_length=20),
        ),
    ]
