# Generated by Django 6.0.2 on 2026-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0002_mediarequest_creators_mediarequest_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarequest',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
