# Generated by Django 6.0.2 on 2026-04-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0003_mediarequest_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarequest',
            name='media_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('tv', 'TV Show'), ('movie', 'Movie'), ('game', 'Game'), ('book', 'Book'), ('wiki', 'Wiki (whole)')], max_length=10),
        ),
    ]
