# Generated by Django 6.0.2 on 2026-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0003_mediarequest_resolution_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarequest',
            name='chosen_category',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mediarequest',
            name='strategy_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mediarequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('pr', 'Processing'), ('c', 'Completed'), ('f', 'Failed'), ('ns', 'Needs Scope'), ('nc', 'No Category')], default='p', max_length=2),
        ),
    ]
