# Generated by Django 4.2.27 on 2025-12-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0003_chapter_annotated_sentences'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='relationship',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='character_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_character_2', to='book_trees.character'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('epub', 'character_1', 'character_2', 'relationship_type')},
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='chapter_found',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='supporting_text',
        ),
    ]
