# Generated by Django 6.0.2 on 2026-02-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0004_alter_relationship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['epub', 'section__order', 'chapter_number']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='narrators',
            field=models.ManyToManyField(blank=True, related_name='narrated_chapters', to='book_trees.character'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='book_trees.epubfile')),
            ],
            options={
                'ordering': ['epub', 'order'],
                'unique_together': {('epub', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book_trees.section'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('epub', 'section', 'chapter_number')},
        ),
    ]
