# Generated by Django 6.0.2 on 2026-02-28 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0005_alter_chapter_options_chapter_narrators_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='syntactic_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='epub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='book_trees.epubfile'),
        ),
    ]
