# Generated by Django 6.0.2 on 2026-03-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0006_character_syntactic_score_alter_relationship_epub'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='relationship_subtype',
            field=models.CharField(blank=True, help_text='More specific relationship label (brother, captor, rival, etc)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='evidence',
            field=models.JSONField(blank=True, default=list, help_text='\n        List of evidence objects:\n        [\n            {\n                "chapter": int,\n                "specific_type": str,\n                "confidence": float,\n                "chunks": [\n                    {\n                        "context": str,\n                        "characters_in_context": [str],\n                        "sentence_index": int\n                    }\n                ]\n            }\n        ]\n        '),
        ),
    ]
