# Generated by Django 6.0.2 on 2026-03-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_trees', '0007_relationship_relationship_subtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entities', models.JSONField(default=list, help_text='\n        spaCy-compatible span format:\n        [{"start": 0, "end": 5, "label": "PERSON"}, ...]\n        ')),
                ('source', models.CharField(blank=True, help_text='Book title or origin', max_length=100)),
                ('labeled_by', models.CharField(blank=True, max_length=100)),
                ('labeled_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('epub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labeled_sentences', to='book_trees.epubfile')),
            ],
        ),
    ]
